# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acoezard <acoezard@student.42nice.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#                                                      #+#    #+#              #
#                                                     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.9"
services:
#==== NGINX ===================================================================#
  nginx:
    container_name: inception_nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 80:80
      - 443:443
    networks:
      - inception
    volumes:
      - www:/var/www/html
    restart: unless-stopped

#==== MARIADB =================================================================#
  mariadb:
    container_name: inception_mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped

#==== WORDPRESS ===============================================================#
  wordpress:
    container_name: inception_wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - www:/var/www/html
    restart: unless-stopped

#==============================================================================#
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_WWW_PATH}
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB_PATH}
      o: bind

  #============================================================================#
networks:
  inception:
    name: inception
    driver: bridge
