# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acoezard <acoezard@student.42nice.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/05 21:49:07 by acoezard          #+#    #+#              #
#    Updated: 2022/04/05 21:49:07 by acoezard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.9"
services:
  #=================================== NGINX ==================================#
  nginx:
    container_name: inception_nginx
    build: requirements/nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    restart: unless-stopped

  #================================== MARIADB =================================#
  mariadb:
    container_name: inception_mariadb
    build: requirements/mariadb
    image: mariadb
    networks:
      - inception
    restart: unless-stopped

  #================================= WORDPRESS ================================#
  wordpress:
    container_name: inception_wordpress
    build: requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  #============================================================================#
#volumes:

  #============================================================================#
networks:
  inception:
    name: inception
    driver: bridge
